language: node_js
node_js:
- '0.8'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g grunt-cli@0.1.x
script:
- grunt continuous
after_success:
- git config --global user.name "Travis"
- git config --global user.email "travis@travis-ci.org"
- grunt release
env:
  global:
    secure: BBiA0UFVe6JJeaxd1vpA2wiuBaKF4ibm8VY+0dbg8zISykd3zqyN1rQpXDthUQNUlBPWn7Iv4IK1JAO6z+vKN72dbAQ6rJo3sWi4Os1kYq/u8MpgZKqlHahKzqfVvmWYhFxbqwrgUHS+Y604FL0YpIdqqbQOjlJA4ssNCdHCbOk=
