language: node_js
node_js:
 - '0.8'

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - npm install -g grunt-cli@0.1.x

script:
 - grunt continuous

after_success:
 - git config --global user.name "Travis-CI"
 - git config credential.helper "store --file=.git/credentials"
 - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
 - grunt release

env:
  global:
    secure: ded8xnv+gGJfN6/zLmAM6sHCg1hQG/5XtHzWQeRUXpxLI8GcUcA4MzVCRO03ttUazqACQMuSx82fwugwIliyBOoPV0IxoHdJKGaFRhDGsWLBy6mEi7C5PBvoNLwtyCugHDVir5z5bfKjjNdCKKa/Mc/Ut+kstune0smoVUIdDhU=
